# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:            pretty
relative_permalinks:  true

# Dependencies
markdown:             kramdown
highlighter:          pygments

# Setup
title:                Kurorak
tagline:              "[inspiring tagline here]"
url:                  http://kurorak.xyz
baseurl:              ""
exclude:              ["Makefile", "Gruntfile.js", "Gemfile", "README.md", "LICENSE", "node_modules", "package.json"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:           _scss
  style:              :compressed

# List of time zones supported in the TZ database
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:             Asia/Jakarta

# Navigational menus
nav:
  - title: about
    url: /about
  - title: music
    url: /music

# About/contact
author:
  name:               Kurorak
  url:                https://twitter.com/Kurorak
  email:              kurorak@outlook.com

# Collections
collections:
  stuff:
    output:           true
    permalink:        /:path/
