# Permalinks
permalink:            pretty

# Dependencies
markdown:             kramdown
highlighter:          pygments

# Setup
title:                Kurorak
tagline:              "[inspiring tagline here]"
description:          "Hello there! I'm Kurorak, and I make dumb music stuff, free for download."
url:                  http://kurorak.xyz
baseurl:              ""
exclude:              ["Makefile", "Gruntfile.js", "Gemfile", "README.md", "LICENSE", "node_modules", "package.json"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:           _scss
  style:              :compressed

# List of time zones supported in the TZ database
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:             Asia/Jakarta

# Navigational menus
nav:
  - title: about
    url: /about
  - title: music
    url: /music

# About/contact
author:
  name:               Kurorak
  url:                https://twitter.com/Kurorak
  links:
    twitter:            https://twitter.com/Kurorak
    bandcamp:           https://kurorak.bandcamp.com/
    soundcloud:         https://soundcloud.com/kurorak
  email:              kurorak@outlook.com

# Collections
collections:
  stuff:
    output:           true
    permalink:        /:path/
